/* CVS $Id: $ */
package uk.ac.osswatch.simal.model; 
import com.hp.hpl.jena.rdf.model.*;
 
/**
 * Vocabulary definitions from src/main/resources/schema/simalOntology.rdf 
 * @author Auto-generated by schemagen on 20 Jul 2008 19:44 
 */
public class SimalOntology {
    /** <p>The RDF model that holds the vocabulary terms</p> */
    private static Model m_model = ModelFactory.createDefaultModel();
    
    /** <p>The namespace of the vocabulary as a string</p> */
    public static final String NS = "http://simal.oss-watch.ac.uk/ns/0.2/simal#";
    
    /** <p>The namespace of the vocabulary as a string</p>
     *  @see #NS */
    public static String getURI() {return NS;}
    
    /** <p>The namespace of the vocabulary as a resource</p> */
    public static final Resource NAMESPACE = m_model.createResource( NS );
    
    public static final Property PERSON_ID = m_model.createProperty( "http://simal.oss-watch.ac.uk/ns/0.2/simal#personId" );
    
    public static final Property PROJECT_ID = m_model.createProperty( "http://simal.oss-watch.ac.uk/ns/0.2/simal#projectId" );
    
}
